### ISSUE TITLE
Stop confusing with Vimscript

### ISSUE THREAD

**Issue by mizlan** [mizlan/dots-nightly#1]
Figure out a way for the repo to show as Lua, because the fact that it is displayed as 100% vimscript right now is very concerning...

**Comment by HereIsKevin** [comment]
Take a look at [GitHub Linguist overrides](https://github.com/github/linguist/blob/master/docs/overrides.md).

**Comment by mizlan** [comment]
Yea I'm aware of that but that would be a workaround. I'm quite sure what I'm doing should work: changing the default branch etc. oh well
